from __future__ import annotations

from typing import Any


def assessment_workspace_records() -> list[dict[str, Any]]:
    """Synthetic credentials for the isolated demo/assessment vault only.

    Production backup/import/export code must not own sample secrets. Keeping the
    dataset here makes demo data explicit, disposable, and easy to exclude from
    real vault flows.
    """
    return [
            dict(
                title='GitHub Admin Portal',
                username='admin@cybervault.local',
                password='G!tHub#2026_XVault',
                category='Work',
                tags='admin,code,privileged,healthy',
                notes='Privileged source-code account. Keep hardware MFA enabled and restrict recovery methods.',
                website='github.com',
                is_favorite=True,
                age_days=8,
            ),
            dict(
                title='Corporate Mail Gateway',
                username='mail.owner@corp.example',
                password='password123',
                category='Education',
                tags='breached,weak,email',
                notes='Mail credential using a weak known pattern. Replace immediately and enforce MFA.',
                website='mail.corp.example',
                is_favorite=False,
                age_days=2,
            ),
            dict(
                title='Cloud Operations Console',
                username='ops@cloud.example',
                password='Winter2024!',
                category='Servers',
                tags='reused,cloud,operations',
                notes='Privileged cloud console account. Reuse detection should prioritize this record.',
                website='cloud.example.com',
                is_favorite=True,
                age_days=18,
            ),
            dict(
                title='Brand Social Console',
                username='social@brand.example',
                password='Winter2024!',
                category='Social',
                tags='reused,marketing,shared-risk',
                notes='Shared social media management account using the same password as a cloud console.',
                website='instagram.com',
                is_favorite=False,
                age_days=21,
            ),
            dict(
                title='Finance Portal',
                username='finance@bank.example',
                password='Tru$tedBank#2026!Qx',
                category='Banking',
                tags='finance,mfa,healthy,critical',
                notes='High-value financial account. Maintain hardware-token MFA and strict recovery controls.',
                website='bank.example.com',
                is_favorite=True,
                age_days=5,
            ),
            dict(
                title='Legacy Mail Archive',
                username='legacy@mail.example',
                password='Qwerty2020',
                category='Email',
                tags='legacy,stale,weak',
                notes='Old archive mailbox with a predictable password. Rotate or disable after review.',
                website='archive-mail.example.com',
                is_favorite=False,
                age_days=128,
            ),
            dict(
                title='Threat Simulation Portal',
                username='bibo_fox',
                password='Ctf-Lab#2026-BlueTeam',
                category='Education',
                tags='lab,portfolio,healthy',
                notes='Security-lab account with stronger password quality used as a healthy comparison.',
                website='tryhackme.com',
                is_favorite=False,
                age_days=35,
            ),
            dict(
                title='Vendor Procurement Portal',
                username='vendor@corp.example',
                password='Vendor2026',
                category='Shopping',
                tags='vendor,metadata-needed,medium-risk',
                notes='Vendor credential missing a verified website field. Complete metadata before report export.',
                website='',
                is_favorite=False,
                age_days=12,
            ),
            dict(
                title='Retired VPN Access',
                username='vpn.retired@corp.example',
                password='RetiredVPN2020!',
                category='Servers',
                tags='retired,vpn,trash,stale',
                notes='Retired remote-access credential kept in Trash to prove safe recovery and purge workflow.',
                website='vpn.old.example.com',
                is_favorite=False,
                age_days=160,
                move_to_trash=True,
            ),
            dict(
                title='HR Payroll Portal',
                username='hr@corp.example',
                password='Welcome2024',
                category='Work',
                tags='hr,breached,weak,high-impact',
                notes='Payroll account with a common password pattern. Replace before operational use.',
                website='payroll.example.com',
                is_favorite=True,
                age_days=74,
            ),
            dict(
                title='Microsoft 365 Admin',
                username='m365.admin@corp.example',
                password='Company2024!',
                category='Email',
                tags='admin,mail,reused,tenant',
                notes='Tenant administrator account. Reused password risk must be remediated first.',
                website='admin.microsoft.example',
                is_favorite=True,
                age_days=44,
            ),
            dict(
                title='Project Operations Admin',
                username='jira.admin@corp.example',
                password='Company2024!',
                category='Work',
                tags='admin,projects,reused',
                notes='Operations admin sharing a password with the Microsoft 365 admin record.',
                website='jira.example.com',
                is_favorite=False,
                age_days=46,
            ),
            dict(
                title='Slack Workspace Owner',
                username='comms@corp.example',
                password='Summer2025!',
                category='Work',
                tags='workspace,breached,reused,comms',
                notes='Collaboration workspace owner account with password reuse exposure.',
                website='slack.com',
                is_favorite=False,
                age_days=31,
            ),
            dict(
                title='Docker Hub Registry',
                username='devops@registry.example',
                password='Summer2025!',
                category='Servers',
                tags='devops,registry,reused,supply-chain',
                notes='Container registry credential sharing a password with the collaboration workspace.',
                website='hub.docker.com',
                is_favorite=False,
                age_days=34,
            ),
            dict(
                title='DNS Registrar',
                username='domains@corp.example',
                password='Dns-Reg!strar#2026-Core',
                category='Work',
                tags='dns,critical,healthy',
                notes='Domain registrar account. Protect with hardware MFA and emergency ownership recovery.',
                website='registrar.example.com',
                is_favorite=True,
                age_days=14,
            ),
            dict(
                title='Stripe Billing Dashboard',
                username='billing@corp.example',
                password='Tr0pical$Billing-2026',
                category='Banking',
                tags='billing,payments,healthy',
                notes='Billing console account with acceptable strength. Confirm least-privilege roles.',
                website='stripe.com',
                is_favorite=True,
                age_days=9,
            ),
            dict(
                title='CRM Sales Portal',
                username='sales@corp.example',
                password='P@ssw0rd',
                category='Work',
                tags='crm,weak,breached,customer-data',
                notes='Customer-data system using a known weak pattern. Rotate and enforce MFA.',
                website='crm.example.com',
                is_favorite=False,
                age_days=11,
            ),
            dict(
                title='Database Admin Console',
                username='dba@db.example',
                password='DbAdmin#2026-Rotate',
                category='Servers',
                tags='database,privileged,rotation-due',
                notes='Database administrator credential. Add break-glass policy and rotation schedule.',
                website='db-admin.example.com',
                is_favorite=True,
                age_days=93,
            ),
            dict(
                title='Backup Management Console',
                username='backup@corp.example',
                password='Backup2020!',
                category='Servers',
                tags='backup,stale,recovery-risk',
                notes='Backup console credential is old and high-impact. Rotate after validating recovery procedures.',
                website='backup.example.com',
                is_favorite=True,
                age_days=190,
            ),
            dict(
                title='Wireless Controller',
                username='netadmin@wlc.local',
                password='NetOps#2026-WiFi',
                category='Servers',
                tags='network,wifi,healthy',
                notes='Wireless controller account with strong password. Verify admin role separation.',
                website='wlc.local',
                is_favorite=False,
                age_days=22,
            ),
            dict(
                title='Endpoint Security Console',
                username='security@edr.local',
                password='EDR-Sentinel#2026',
                category='Work',
                tags='security,edr,healthy',
                notes='Endpoint-security console. Keep emergency access and audit logging enabled.',
                website='edr.example.com',
                is_favorite=True,
                age_days=7,
            ),
            dict(
                title='API Gateway Console',
                username='api-owner@corp.example',
                password='Gateway2024!',
                category='Servers',
                tags='api,medium-risk,rotation-due',
                notes='API gateway admin account. Rotate and verify token inventory after password change.',
                website='gateway.example.com',
                is_favorite=False,
                age_days=86,
            ),
            dict(
                title='CI Deployment Service Account',
                username='svc-ci@corp.example',
                password='SvcDeploy2023!',
                category='Servers',
                tags='service-account,ci,stale',
                notes='Service account used by deployment workflows. Move to scoped token or managed identity.',
                website='ci.example.com',
                is_favorite=False,
                age_days=155,
            ),
            dict(
                title='Code Signing Portal',
                username='release@corp.example',
                password='CodeSign#2026-Critical',
                category='Work',
                tags='release,code-signing,critical,healthy',
                notes='Release-signing account. Treat as critical and require dual-control approval.',
                website='codesign.example.com',
                is_favorite=True,
                age_days=17,
            ),
            dict(
                title='Knowledge Portal Admin',
                username='knowledge.admin@corp.example',
                password='Password1',
                category='Education',
                tags='knowledge,weak,breached',
                notes='Knowledge portal account using a known compromised pattern. Replace immediately.',
                website='knowledge.example.com',
                is_favorite=False,
                age_days=28,
            ),
            dict(
                title='eCommerce Merchant Center',
                username='seller@shop.example',
                password='Merchant#2026-Live',
                category='Shopping',
                tags='merchant,payments,healthy',
                notes='Merchant account with payment exposure. Confirm alerting and account recovery settings.',
                website='merchant.example.com',
                is_favorite=False,
                age_days=19,
            ),
            dict(
                title='Helpdesk Admin Panel',
                username='support@corp.example',
                password='Helpdesk2024!',
                category='Work',
                tags='helpdesk,admin,rotation-due',
                notes='Helpdesk admin account can reset users. Enforce MFA and audit privileged actions.',
                website='helpdesk.example.com',
                is_favorite=False,
                age_days=101,
            ),
            dict(
                title='Personal Portfolio Hosting',
                username='bibo_fox@portfolio.example',
                password='BiboPortfolio#2026',
                category='Personal',
                tags='portfolio,personal,healthy',
                notes='Portfolio hosting account with healthy password strength and clear metadata.',
                website='portfolio.example.com',
                is_favorite=False,
                age_days=13,
            ),
            dict(
                title='Red Team Lab Console',
                username='analyst.redteam@lab.example',
                password='123456',
                category='Education',
                tags='lab,weak,breached,critical-finding',
                notes='High-risk lab credential used to verify weak-password detection and prioritization.',
                website='lab.example.com',
                is_favorite=False,
                age_days=3,
            ),
            dict(
                title='Old FTP Server',
                username='ftp.legacy@corp.example',
                password='FTP2020!',
                category='Servers',
                tags='retired,ftp,trash,legacy',
                notes='Legacy FTP access moved to Trash to demonstrate safer retirement workflow.',
                website='ftp.legacy.example.com',
                is_favorite=False,
                age_days=220,
                move_to_trash=True,
            ),
        ]
