[pytest]
addopts = --assert=plain -p no:ddtrace -p no:pytest_jsonreport -p no:json-report -p no:cov -p no:anyio -p no:asyncio -p no:metadata -p no:Faker -p no:faker
python_files = tests/test_*.py
testpaths = tests
