from __future__ import annotations

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.project_cleaner import clean_project  # noqa: E402


EVIDENCE = ROOT / "evidence"
BUILD_LOG = EVIDENCE / "build_output.txt"

COMMANDS: tuple[tuple[str, list[str], Path], ...] = (
    (
        "pytest full suite",
        [sys.executable, "-m", "pytest", "-q"],
        EVIDENCE / "pytest_output.txt",
    ),
    (
        "release preflight",
        [sys.executable, "tools/release_preflight.py"],
        EVIDENCE / "release_preflight_output.txt",
    ),
)


def _write_header(path: Path, title: str, command: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    command_text = " ".join(command)
    separator = "=" * 72
    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()

    path.write_text(
        f"CyberVault X Evidence Run\n"
        f"Title: {title}\n"
        f"Generated UTC: {generated_at}\n"
        f"Command: {command_text}\n"
        f"Working directory: <project-root>\n"
        f"{separator}\n",
        encoding="utf-8",
    )


def _append_build_log(message: str) -> None:
    BUILD_LOG.parent.mkdir(parents=True, exist_ok=True)
    with BUILD_LOG.open("a", encoding="utf-8") as fh:
        fh.write(message.rstrip() + "\n")


def run_and_capture(title: str, command: list[str], output_path: Path) -> int:
    _write_header(output_path, title, command)

    result = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    with output_path.open("a", encoding="utf-8") as fh:
        if result.stdout:
            fh.write(result.stdout)
        if result.stderr:
            fh.write("\n[stderr]\n")
            fh.write(result.stderr)
        fh.write(f"\nExit code: {result.returncode}\n")

    status = "PASS" if result.returncode == 0 else "FAIL"
    line = f"[{status}] {title} -> {output_path.relative_to(ROOT)}"
    print(line)
    _append_build_log(line)

    return result.returncode


def main() -> int:
    failures = 0

    _write_header(
        BUILD_LOG,
        "release evidence generator",
        [sys.executable, "tools/generate_release_evidence.py"],
    )

    # Run tests first, then clean generated bytecode/cache folders before
    # release_preflight so the release evidence mirrors the final ZIP state.
    title, command, output_path = COMMANDS[0]
    if run_and_capture(title, command, output_path) != 0:
        failures += 1

    clean_result = clean_project(ROOT)
    clean_line = f"[INFO] cleaned generated files before preflight: {clean_result}"
    print(clean_line)
    _append_build_log(clean_line)

    title, command, output_path = COMMANDS[1]
    if run_and_capture(title, command, output_path) != 0:
        failures += 1

    ruff_path = EVIDENCE / "ruff_output.txt"
    _write_header(
        ruff_path,
        "ruff lint check",
        [sys.executable, "-m", "ruff", "check", "."],
    )

    ruff = subprocess.run(
        [sys.executable, "-m", "ruff", "check", "."],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    with ruff_path.open("a", encoding="utf-8") as fh:
        if ruff.stdout:
            fh.write(ruff.stdout)
        if ruff.stderr:
            fh.write("\n[stderr]\n")
            fh.write(ruff.stderr)

        ruff_output = ruff.stderr + ruff.stdout
        if ruff.returncode == 1 and "No module named ruff" in ruff_output:
            fh.write(
                "\nRuff is declared in requirements-dev.txt. "
                "Install dev requirements with: "
                "python -m pip install -r requirements-dev.txt\n"
            )

        fh.write(f"\nExit code: {ruff.returncode}\n")

    ruff_status = "PASS" if ruff.returncode == 0 else "MANUAL"
    ruff_line = f"[{ruff_status}] ruff lint check -> {ruff_path.relative_to(ROOT)}"
    print(ruff_line)
    _append_build_log(ruff_line)

    final_line = (
        "[PASS] release evidence generation completed"
        if failures == 0
        else "[FAIL] release evidence generation completed with errors"
    )
    print(final_line)
    _append_build_log(final_line)

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())