from __future__ import annotations

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from tools.project_cleaner import clean_project  # noqa: E402

EVIDENCE = ROOT / 'evidence'

COMMANDS: tuple[tuple[str, list[str], Path], ...] = (
    ('pytest full suite', [sys.executable, '-m', 'pytest', '-q'], EVIDENCE / 'pytest_full_output.txt'),
    ('release preflight', [sys.executable, 'tools/release_preflight.py'], EVIDENCE / 'release_preflight_output.txt'),
)


def _write_header(path: Path, title: str, command: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f'CyberVault X Evidence Run\n'
        f'Title: {title}\n'
        f'Generated UTC: {datetime.now(timezone.utc).replace(microsecond=0).isoformat()}\n'
        f'Command: {' '.join(command)}\n'
        f'Working directory: <project-root>\n'
        f'{'=' * 72}\n',
        encoding='utf-8',
    )


def run_and_capture(title: str, command: list[str], output_path: Path) -> int:
    _write_header(output_path, title, command)
    result = subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)
    with output_path.open('a', encoding='utf-8') as fh:
        if result.stdout:
            fh.write(result.stdout)
        if result.stderr:
            fh.write('\n[stderr]\n')
            fh.write(result.stderr)
        fh.write(f'\nExit code: {result.returncode}\n')
    print(f'[{"PASS" if result.returncode == 0 else "FAIL"}] {title} -> {output_path.relative_to(ROOT)}')
    return result.returncode


def main() -> int:
    failures = 0
    # Run tests first, then clean generated bytecode/cache folders before
    # release_preflight so the release evidence mirrors the final ZIP state.
    title, command, output_path = COMMANDS[0]
    if run_and_capture(title, command, output_path) != 0:
        failures += 1
    clean_result = clean_project(ROOT)
    print(f'[INFO] cleaned generated files before preflight: {clean_result}')
    title, command, output_path = COMMANDS[1]
    if run_and_capture(title, command, output_path) != 0:
        failures += 1
    ruff_path = EVIDENCE / 'ruff_output.txt'
    _write_header(ruff_path, 'ruff lint check', [sys.executable, '-m', 'ruff', 'check', '.'])
    ruff = subprocess.run([sys.executable, '-m', 'ruff', 'check', '.'], cwd=ROOT, text=True, capture_output=True, check=False)
    with ruff_path.open('a', encoding='utf-8') as fh:
        if ruff.stdout:
            fh.write(ruff.stdout)
        if ruff.stderr:
            fh.write('\n[stderr]\n')
            fh.write(ruff.stderr)
        if ruff.returncode == 1 and 'No module named ruff' in (ruff.stderr + ruff.stdout):
            fh.write('\nRuff is declared in requirements-dev.txt. Install dev requirements with: python -m pip install -r requirements-dev.txt\n')
        fh.write(f'\nExit code: {ruff.returncode}\n')
    print(f'[{"PASS" if ruff.returncode == 0 else "MANUAL"}] ruff lint check -> {ruff_path.relative_to(ROOT)}')
    return 1 if failures else 0


if __name__ == '__main__':
    raise SystemExit(main())
